title: IT-Blog
description: "Trang Blog Cho Người Mới Bắt Đầu Học Code "
author:
  name: "IT-Blog"
  email: "vontph18623@fpt.edu.vn"
  url: "https://vontph18623.github.io/Blog-IT/"

baseurl: "https://vontph18623.github.io/Blog-IT/"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Nguyen Tien Vo"
year : "2021"
